POST http://localhost:3000/start
Content-Type: application/json

{
    "lambda":20,
    "time": 10,
    "name": "testExperiment",
    "url": {
        "get": "http://127.0.0.1:8888/status",
        "post":  "http://127.0.0.1:8888/status",
        "delete":  "http://127.0.0.1:8888/status",
        "put":  "http://127.0.0.1:8888/status",
        "patch":  "http://127.0.0.1:8888/status"
    }
}

###

POST http://localhost:3000/start
Content-Type: application/json

{
    "lambda":20,
    "time": 60,
    "name": "testExperiment",
    "wot":true,
    "url": {
        "get": "http://192.168.1.242:3333/mockapi/properties/get-status",
        "post":  "http://192.168.1.242:3333/mockapi/actions/post-status",
        "delete":  "http://192.168.1.242:3333/mockapi/actions/delete-status",
        "put":  "http://192.168.1.242:3333/mockapi/properties/put-status",
        "patch":  "http://192.168.1.242:3333/mockapi/properties/put-status"
    }
}

###

POST http://localhost:3000/start
Content-Type: application/json

{
    "number-of-edges":1,
    "time": 10,
    "name": "raw-timeout",
    "replication": 1,
    "accelerometer": {
      "withFeatures": false,
      "url":  "https://modron-api.iot-prism-lab.cs.unibo.it/accelerationRawExtract",
      "perEdgeNode": 3,
      "samples": 2500,
      "features": 6,
      "periodicity": 10000
    },
    "acoustic-emission": {
      "withFeatures": false,
      "url":  "https://modron-api.iot-prism-lab.cs.unibo.it/acousticRawExtract",
      "perEdgeNode": 3,
      "features": 11,
      "samples": 2500,
      "periodicity": 10000
    }
}

###

POST http://130.136.2.155:3000/start
Content-Type: application/json

{
    "number-of-edges":1,
    "time": 3600,
    "name": "raw-timeout",
    "replication": 1,
    "accelerometer": {
      "withFeatures": false,
      "url":  "https://modron-api.iot-prism-lab.cs.unibo.it/accelerationRawExtract",
      "perEdgeNode": 3,
      "samples": 2500,
      "features": 6,
      "periodicity": 10000
    },
    "acoustic-emission": {
      "withFeatures": false,
      "url":  "https://modron-api.iot-prism-lab.cs.unibo.it/acousticRawExtract",
      "perEdgeNode": 3,
      "features": 11,
      "samples": 2500,
      "periodicity": 10000
    }
}